### ISSUE TITLE
Not working (100%) with latest k6 HandleSummary output file

### ISSUE THREAD

**Issue by aidanhyland** [szboynono/k6-html-reporter#1]
Hi, 

Great work on this. 

Just wanted to call out with K6's latest update https://k6.io/docs/results-visualization/end-of-test-summary#handlesummary-callback, the summary JSON file differs in structure. 

The HTML converter might want to be updated? You can see from the screen grab. Let me know what you think?

![K6-Summary-Report](https://user-images.githubusercontent.com/18060197/109820533-c3842a00-7c3d-11eb-843e-0832c5770960.png)

**Comment by szboynono** [comment]
Thanks for the update! yea, the tool won't work with that update from k6. I will look into it

**Comment by szboynono** [comment]
Looks like the use of  --summary-export flag is discouraged, I will do an update to the tool so it will accept the new format, we will have to use  handleSummary() to generate JSON reports from now on

**Comment by aidanhyland** [comment]
Agree, I've changed my scripts to use this new function.

**Comment by szboynono** [comment]
closing this with this PR https://github.com/szboynono/k6-html-reporter/pull/2
